import NavMenu from "@/components/Header/Nav";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SubHeader from "@/components/Header/SubHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Xtreme-Jumps",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="clearfix wrapper">
          <header role="banner" className="clearfix header">
            <NavMenu />
          </header>
          <SubHeader />
          <div className="left-menu">
          <aside role="complementary" className="side-menus">
            <h2 className="header_left">Discord</h2>
            <br />
            <div className="center-content">
              <a
                className="bbcode"
                href="https://web.archive.org/web/20220420134731/https://discordapp.com/channels/378668439243456512/378668439243456514"
                rel="external"
                target="_blank"
              >
                <img
                  src="https://web.archive.org/web/20220420134731im_/https://xtreme-jumps.eu/img/Discord2.jpg"
                  className="bbcode"
                  alt=""
                />
              </a>
              <a
                className="bbcode"
                href="https://web.archive.org/web/20220420134731/https://discord.gg/2du9kt8"
                rel="external"
                target="_blank"
              >
                Invitation
              </a>
            </div>
            <br />
          </aside>
        </div>
        {children}
        <div className="right-menu"></div>
        </div>
      </body>
    </html>
  );
}
